### ISSUE TITLE
GPL & MIT

### ISSUE THREAD

**Issue by zbeekman** [Fortran-FOSS-Programmers/FoXy#1]
I may be mistaken, but I’m pretty sure that since GPL is “copy left” you are violating the GPL license by also licensing it under the other more permissive licenses… I’m not an expert but it might be safer to just use MIT/BSD…

**Comment by szaghi** [comment]
@zbeekman 

I am confused (do you see? :-) ) about licensing.

I followed some hints on web, in particular [this](http://programmers.stackexchange.com/questions/121998/mit-vs-bsd-vs-dual-license), response 35.

Where I understand that MIT, BSD-x could be not the same...

One thing that I suppose to understand (seeing some foss codes in the web, but now I am in doubt) is:

> your code (let us say code of the day `X`) can be distributed under difference licenses (even one violating other, this is crucial: is it true?); once the user get the code and do his/her stuffs with it, he/she must select the license preferred. All the subsequent usages/modifications of the user (say code of day `Y`) must go under the license he/she selected, thus the code `X` and the code `Y` can become incompatible. 

I am right or not? Please, someone with more experience (@zbeekman can you confirm or kill me?) give us the answer.

In the case I am wrong, sure I will likely drop GPL, on the contrary I prefer to maintain also GPL.

What do you think?

**Comment by zbeekman** [comment]
reading the link you sent, I think you might be right! I’m no expert though…

**Comment by szaghi** [comment]
I reopen the issue... maybe I could have bring confusion to you :-)

I would like to know the opinions of others.

**Comment by milancurcic** [comment]
AFAIK, the copyright owner has the right to release software under any license or even multiple licenses. The user chooses one license that works for them. Even if licenses offered are not compatible between each other, the software release is licensed under a single license, the one that the user chose.

**Comment by szaghi** [comment]
Thank you @milancurcic 

This is a second _evidence_ I was searching for.

I close the issue, but I will reopen if other dubts araise.

Thank you all.
